"""add parameter history fields and chat history link

Revision ID: 6bfdb667f5f1
Revises: 
Create Date: 2025-05-08 23:46:18.383046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bfdb667f5f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('parameter_history_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_histories_parameter_history_id'), 'chat_histories', ['parameter_history_id'], unique=False)
    op.create_foreign_key(None, 'chat_histories', 'parameter_histories', ['parameter_history_id'], ['id'])
    op.add_column('parameter_histories', sa.Column('session_uuid', sa.String(length=36), nullable=False))
    op.add_column('parameter_histories', sa.Column('title', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_parameter_histories_session_uuid'), 'parameter_histories', ['session_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parameter_histories_session_uuid'), table_name='parameter_histories')
    op.drop_column('parameter_histories', 'title')
    op.drop_column('parameter_histories', 'session_uuid')
    op.drop_constraint(None, 'chat_histories', type_='foreignkey')
    op.drop_index(op.f('ix_chat_histories_parameter_history_id'), table_name='chat_histories')
    op.drop_column('chat_histories', 'parameter_history_id')
    # ### end Alembic commands ###
